name: go
description: Go Motel Guide Project
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  core:
    path: ../../packages/core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_flavorizr: ^2.2.2

  flutter_lints: ^3.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true


# flutter pub run flutter_flavorizr
flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"

  flavors:
    prod:
      app:
        name: "Go"
      android:
        applicationId: "br.com.moteis.go"
        icon: "assets/icon/go_prd.png"
        launchScreen: "assets/splash/go_splah.png"
      ios:
        bundleId: "br.com.moteis.go"
        icon: "assets/icon/go_prd.png"

    dev:
      app:
        name: "Go - dev"
      android:
        applicationId: "br.com.moteis.go.dev"
        icon: "assets/icon/go_dev.png"
        launchScreen: "assets/splash/go_splah.png"
      ios:
        bundleId: "br.com.moteis.go.dev"
        icon: "assets/icon/go_dev.png"

    hml:
      app:
        name: "Go - hml"
      android:
        applicationId: "br.com.moteis.go.hml"
        icon: "assets/icon/go_hml.png"
        launchScreen: "assets/splash/go_splah.png"
      ios:
        bundleId: "br.com.moteis.go.hml"
        icon: "assets/icon/go_hml.png"

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#FF0000"
  color_dark: "#303030"
  image: assets/splash/go_splash.png
  fullscreen: true
  android_12:
    image: assets/splash/go_android12.png
    color: "#FF0000"
    color_dark: "#303030"