name: locator_native
description: Locator native package
publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../core
  locator_common:
    path: ../locator_common


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
